name: MetaHider
description: Hide information from modded clients that vanilla clients cannot see
author: Raus
main: com.raus.metaHider.Main
version: 1.0
api-version: 1.15
depend: [ProtocolLib]

commands:
  metahider:
    description: Meta Hider
    default: true
    usage: "Usage: /metahider [info|reload]"

permissions:
  metahider.reload:
    default: op
    description: Allows you to reload the config